import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../../../agent.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../../../assets/css/styles.css', import.meta.url), 'utf8');
const accessibilityCss = fs.readFileSync(new URL('../../../assets/css/agent-accessibility.css', import.meta.url), 'utf8');
const apiClient = fs.readFileSync(new URL('../../../assets/js/api.js', import.meta.url), 'utf8');
const settings = fs.readFileSync(new URL('../../../settings.html', import.meta.url), 'utf8');
const apiRoutes = fs.readFileSync(new URL('../../src/routes/api.js', import.meta.url), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert.ok(script, 'agent inline script is required');
new Function(script);
new Function(apiClient);

for (const text of ['选择老人', '新对话', '已记住的信息', '要记住这件事吗', '读取依据']) assert.match(html, new RegExp(text));
for (const text of ['当前结论', '关键数据', '下一步行动', '需要帮助时', '查看依据']) assert.match(html, new RegExp(text));
for (const text of ['待处理健康事项', '今天稍后', '明早', '自选时间', '是本次复测', '哪里需要改进']) assert.match(html, new RegExp(text));
for (const text of ['选择复测时间', '不会自动保存', '确认安排', '暂不安排']) assert.match(html, new RegExp(text));
for (const text of ['做什么：', '做多久：', '如何记录：', '何时复测：', '观察指标：', '证据来源：', '停止并就医：', '确认创建干预', '确认记录']) assert.match(html, new RegExp(text));
for (const text of ['看看我的总体健康', '看看最近血压', '生成今日健康方案', '我想问一个健康问题', '今日健康贴士']) assert.ok(html.includes(text), `${text} 单入口内容缺失`);
assert.ok(!html.includes('id="mode-tabs"'), '三模式标签应彻底移除');
assert.ok(!html.includes('data-tab="plan"') && !html.includes('data-tab="qa"') && !html.includes('data-tab="tip"'), '不应保留模式切换按钮');
assert.ok(html.includes('/api/agent/daily-tip?subject_user_id='), '每日贴士接口未接入');
for (const text of ['高压（收缩压）', '低压（舒张压）', '毫米汞柱', '毫摩尔/升', '健康智能分析']) assert.ok(html.includes(text), `${text} 中文展示映射缺失`);
assert.ok(!html.includes("' · ' + llmMeta.model"), '老人端不应显示英文模型名称');
assert.ok(!html.includes('把上面的建议设为今日提醒'), '重复的今日提醒提示应移除');
for (const endpoint of ['/api/chat/conversations', '/api/agent/memories', '/api/actions/', '/regenerate']) assert.ok(html.includes(endpoint), `${endpoint} missing`);
for (const endpoint of ['/api/actions/interventions', '/executions']) assert.ok(html.includes(endpoint), `${endpoint} intervention endpoint missing`);
for (const field of ['conversation_id', 'subject_user_id', 'client_request_id']) assert.match(html, new RegExp(field));
assert.match(html, /idempotency_key/);
assert.match(html, /\/cancel/);
assert.match(css, /\.agent-context-bar/);
assert.match(css, /\.agent-memory-candidate/);
assert.match(css, /\.agent-action-preview-controls/);
assert.match(css, /\.agent-health-card/);
assert.match(css, /\.agent-health-card\.tone-urgent/);
assert.match(css, /\.agent-inbox/);
assert.match(css, /\.agent-schedule-picker/);
assert.match(css, /\.agent-schedule-options/);
assert.match(css, /\.plan-card-mini\{[\s\S]*?display:grid!important/);
assert.match(css, /\.agent-clarification-card/);
assert.match(css, /\.agent-facts\{[^}]*grid-template-columns:repeat\(3/);
assert.match(css, /font-size:18px/);
assert.match(css, /min-height:\s*48px/);
assert.ok(html.includes('id="agent-splitter"'), '左右宽度调节控件缺失');
assert.ok(html.includes('class="agent-console"'), '智能管家工作台缺失');
assert.ok(html.includes('class="agent-control-rail"'), '历史会话侧栏缺失');
assert.ok(html.includes('小康健康管家') && html.includes('健康能力') && html.includes('安全运行中'), '管理栏关键信息缺失');
assert.ok(!html.includes('id="agent-workspace-height-resizer"'), '单滚动模式不应保留高度调节控件');
assert.ok(!html.includes('id="chat-height-resizer"') && !html.includes('id="plan-height-resizer"'), '不应保留左右两套互相冲突的高度控件');
for (const text of ['历史记录', 'agent-conversation-list', '新建健康对话', '实时健康记录', '趋势与风险发现', '和小康聊一聊', '今日健康安排']) assert.ok(html.includes(text), `${text} 智能管家内容缺失`);
assert.ok(html.includes('id="agent-plan-toggle"') && html.includes('id="agent-plan-close"'), '今日安排抽屉开关缺失');
assert.match(html, /data-conversation-id/);
assert.match(css, /overflow-y:scroll!important/);
assert.match(css, /chat-history::-webkit-scrollbar/);
assert.ok(!html.includes('class="agent-layout-toolbar"'), '顶部工作区大小工具条应移除');
assert.match(html, /xiaokang-agent-split-ratio-v2/);
assert.match(html, /ArrowLeft/);
assert.match(html, /ArrowRight/);
assert.match(css, /\.agent-height-resizer/);
assert.match(css, /cursor:row-resize/);
assert.match(css, /\.agent-console/);
assert.match(css, /\.agent-control-rail/);
assert.match(css, /@media\(max-width:1260px\)/);
assert.match(css, /\.agent-chat-composer/);
assert.match(css, /overflow:visible!important/);
assert.match(css, /\.agent-workspace-height-resizer/);
for (const text of ['agent-run-progress', 'agent-stop-wait', '正在读取健康记录', '正在分析趋势和风险', '停止等待']) assert.ok(html.includes(text), `${text} 运行状态内容缺失`);
assert.ok(html.includes('assets/css/agent-accessibility.css'), '适老可读性覆盖样式未加载');
assert.match(accessibilityCss, /font-size:16px!important/);
assert.match(accessibilityCss, /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
for (const text of ['APIError', 'CLIENT_TIMEOUT', 'requestId', 'retryable', 'AbortSignal']) assert.ok(apiClient.includes(text), `${text} API 错误与取消契约缺失`);
for (const text of ['/api/chat/stream', '/api/chat/cancel', 'API.stream', 'event === \'delta\'']) assert.ok(html.includes(text) || apiClient.includes(text), `${text} 流式取消契约缺失`);
for (const text of ['text/event-stream', 'X-Accel-Buffering', 'registerAgentRun', 'AGENT_CANCELLED']) assert.ok(apiRoutes.includes(text), `${text} 服务端流式取消契约缺失`);
for (const text of ['agent-trend-chart', '趋势引用日期', '查看依据与可信度', '不能替代医生诊断']) assert.ok(html.includes(text) || accessibilityCss.includes(text), `${text} 趋势与可信度展示缺失`);
for (const text of ['模型调用监控', 'failure_count', 'fallback_count', 'total_tokens', 'estimated_cost_cny']) assert.ok(settings.includes(text), `${text} 模型监控界面缺失`);

console.log('agent v2 frontend static acceptance: PASS');
